image: lorisleiva/laravel-docker:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

phpunit:
  stage: test
  script:
    - rm -Rf ./vendor
    - php -v
    - composer install
    - composer phpcs

analysis:
  stage: test
  script:
    - php ./vendor/bin/phpunit --coverage-text --coverage-cobertura=coverage.cobertura.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml
