name: Testing

on: [push]

jobs:
#  linter:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: "laravel-pint"
#        uses: aglipanci/laravel-pint-action@2.0.0
#        with:
#          preset: laravel
#          verboseMode: true
#          testMode: true
#          configPath: "vendor/my-company/coding-style/pint.json"
#          pintVersion: 1.8.0
#          onlyDirty: true

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Installing dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.2
          php_extensions: "json zip sodium pcntl bcmath"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: stan
        run: "./vendor/bin/phpstan analyse --memory-limit=2G"

#  phpinsights:
#    name: PHP-Insights
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: PHP-Insights
#        uses: docker://tienvx/phpinsights-action

# stan
#insights
